### ISSUE TITLE
There is no error handler at the page of User registration

### ISSUE THREAD

**Issue by userlocalhost** [dmm-com/pagoda#110]
## Background / Problem
When user try to register a new user with empty form. Server responds with HTTP 400 error. But no error message will be revealed because there is no error handling implementation in the processing of JavaScript.

## Requirements of fix
At least, AirOne should implement an error handler to be able to let user to know followings.

* What problem was happened.
* What should user do.

**Comment by syucream** [comment]
I created 2 PRs https://github.com/dmm-com/airone/pull/112 , https://github.com/dmm-com/airone/pull/113 to improve user experiences. How about them?

BTW Django supports an abstracted form stuff like `forms.Form` class. I think its a recommended way to represent a rich form to integrate it with template, perform complicated validation logic, etc 👀  
https://docs.djangoproject.com/en/3.1/topics/forms/

**Comment by syucream** [comment]
duplicated https://github.com/dmm-com/airone/issues/80
