### ISSUE TITLE
JavaScript error will be happened at entry edit page when attribute value has back-slash

### ISSUE THREAD

**Issue by userlocalhost** [dmm-com/pagoda#14]
## way of reproducing
1. Make an entity (E1) that has attribute typed `array_string`
2. Make an entry(e1) of E1 and set value (a backslash `\`) to the attribute.
3. Show edit tab of e1, then attribute value couldn't be shown (because of a JavaScript problem was happend).

(c.f. https://github.com/dmm-com/airone/pull/13#issuecomment-589575950)

**Comment by takano32** [comment]
c.f. #18
