### ISSUE TITLE
(BUG) We couldn't create/update entry when array_string attribute is set as mandatory

### ISSUE THREAD

**Issue by userlocalhost** [dmm-com/pagoda#18]
When an Entity has attribute of array_string type as mandatory, an entry of this entity cannot create (or update) even though attribute values are set as below. 
<img width="1196" alt="スクリーンショット 2020-03-09 12 54 15" src="https://user-images.githubusercontent.com/469934/76181691-48905b00-6205-11ea-9655-71ed9a12965a.png">

**Comment by takano32** [comment]
see also #13

**Comment by userlocalhost** [comment]
We realized that following bug is remained.

* A mandatory attribute can be updated with blank value by specifying `- NOT SET-` parameter which describes there is no valid entry.
