### ISSUE TITLE
Upgrade django to the latest version of v2.2.x

### ISSUE THREAD

**Issue by userlocalhost** [dmm-com/pagoda#56]
The current version of django that AirOne uses is v1.11(LTS). But it is obsoleted and also its support has already been ended.
(c.f. https://www.djangoproject.com/download/)

We should upgrade it to next LTS (v2.2.x).

**Comment by hinashi** [comment]
It will be closed because it has already been done below.
https://github.com/dmm-com/airone/pull/93
