### ISSUE TITLE
Filtering JavaScript escape strings

### ISSUE THREAD

**Issue by ritsuxis** [dmm-com/pagoda#618]
# Problem

JavaScript escape characters are not filtered in the program and may be displayed improperly when included in a string.

# Example

## show entry page
![スクリーンショット 2022-09-12 16 28 21](https://user-images.githubusercontent.com/49955721/189596919-37574b9d-6055-455e-a22c-02d64157964f.png)

## edit entry page
The value of the `entry` attribute is not displayed.

![スクリーンショット 2022-09-12 16 28 32](https://user-images.githubusercontent.com/49955721/189596927-19c9c851-19b0-4a1a-b821-c1f8a66e8a62.png)

# HowToFix

 Add `escapejs` filters to the part of the `js.html` file where the string is embedded in Django's `{{ value }}` notation.

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#escapejs

**Comment by hinashi** [comment]
close: https://github.com/dmm-com/airone/pull/622
