### ISSUE TITLE
It is possible to create an entry with a blank name

### ISSUE THREAD

**Issue by ritsuxis** [dmm-com/pagoda#627]
# Problem

The name of the entry must be entered on the front end, but an empty entry can be created by including only spaces (half-width` ` or double-byte`　`) in the name.
Entries of including only spaces are same name, so `    ` and `　　　　　 ` are duplicate.

- The case of empty name(normal)
![スクリーンショット 2022-09-15 13 01 02](https://user-images.githubusercontent.com/49955721/190312515-f6f5bef3-115b-4faf-ab5c-650628facb45.png)

- Include double-byte spaces entry (clickable)
![スクリーンショット 2022-09-15 13 01 22](https://user-images.githubusercontent.com/49955721/190312534-b094768f-e205-431a-be93-cad61cf9d65d.png)

- Include only half-width spaces entry(non-clickable)
![スクリーンショット 2022-09-15 13 02 16](https://user-images.githubusercontent.com/49955721/190312583-b5fababa-f76e-47e7-953f-e394d92fcf73.png)

- Empty name entry
![スクリーンショット 2022-09-15 13 22 29](https://user-images.githubusercontent.com/49955721/190313891-28b40645-bcd6-4872-94e6-0f3aec1ac673.png)

**Comment by hinashi** [comment]
Thanks for finding the bug!
Since space (half-width` ` or double-byte`　`)  are not assumed in the entry name
I would like to have validate in both the frontend and backend.
